CREATE TABLE public.g_sequence (
                                   id int8 NOT NULL,
                                   g_key varchar(255) NOT NULL,
                                   subkey varchar(255) NULL,
                                   startnum int8 NULL,
                                   step int4 NULL,
                                   maxnum int8 NULL,
                                   dayresetting varchar(1) NULL,
                                   lastday varchar(255) NULL,
                                   value int8 NULL,
                                   insert_id int8 NULL,
                                   insert_ymd varchar(255) NULL,
                                   update_ymd varchar(255) NULL,
                                   update_id int8 NULL,
                                   remark varchar(255) NULL,
                                   remark1 varchar(255) NULL,
                                   remark2 varchar(255) NULL,
                                   remark3 varchar(255) NULL,
                                   remark4 varchar(255) NULL,
                                   remark5 varchar(255) NULL,
                                   effective int4 NULL,
                                   update_flag int4 NULL,
                                   CONSTRAINT g_sequence_pkey PRIMARY KEY (id)
);